spring:
  datasource:
    url: jdbc:postgresql://postgre.caqttrjbwp7e.eu-west-2.rds.amazonaws.com:5432/allinonce
    username: sefakpsz
    password: wordigoteam1907
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect