spring:
  datasource:
    url: jdbc:postgresql://javapostgre.caqttrjbwp7e.eu-west-2.rds.amazonaws.com:5432/jwt_security
    username: sefakpsz
    password: Sefa1907?
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect